[package]
name = "wdg-base64"
version = "0.1.0"
authors = ["Grigoriy Baranov <baranov@w3m.co>"]
edition = "2018"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
